---
- name: this playbook installs the httpd
  hosts: appservers 
  become: true
  tasks:
  - name: update apt cache
    apt: 
      update_cache: yes
      
  - name: install package
    apt: 
      name: apache2
      state: present

  - name: service start
    service: 
      name: apache2
      state: started 
