---
- name: this playbook unistall the httpd packages in redhat
  hosts: webservers
  become: true
  tasks:
  - name: stopping httpd service 
    service: 
      name: httpd
      state: stopped 
  
  - name: unistall the packages
    yum:
      name: httpd
      state: removed 
