---
- name: this playbook installs the httpd
  hosts: appservers 
  become: true
  tasks:
  - name: start apache2
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"

  - name: start the service
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: unistall package
    apt: 
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"

  - name: install package
    yum:
      name: httpd
      state: removed
    when: ansible_os_family == "RedHat"
