pipeline{
    agent {
        label 'qa'
    }
    
        stages{
            stage('System-Details'){
                steps{
                    sh '''
                    echo '"SYSTEM DETAILS"'
                    uname -a
                    '''
                }
            }
            stage('Build-Memory details'){
                steps{
                    sh '''
                    echo "MEMORY DETAILS"
                    free
                    '''
                }
            }
            stage('Build-CPU details'){
                steps{
                    sh '''
                    echo "CPU DETAILS"
                    lscpu
                    '''
                }
            }
            stage('Date'){
                steps{
                    sh '''
                    echo "TODAYS DATE"
                    date
                    '''
                }
            }
            stage('Build-Process command'){
                steps{
                    sh '''
                    echo "Process command"
                    ps -ef | head
                    '''
                }
            }

        }
}